### ISSUE TITLE
Increase indentation on procedures?

### ISSUE THREAD

**Issue by blacksunrise56** [alefragnani/atom-language-pascal#17]
In the settings file at [line 5](https://github.com/alefragnani/atom-language-pascal/blob/master/settings/language-pascal.cson#L5) `procedure` is set to increase indentation. Is there a reason to do this? the indentation inside procedures should be marked by the `begin`'s or `end`'s (or `var`,`const`,etc.), the way it is right now typing:
``` pascal
public
  procedure something();
```
Will make the next line:
``` pascal
public
  procedure something();
    procedure something2();
```

And:
``` pascal
procedure something();
  begin // misplaced begin
  writeln('hello');
end;
```

**Comment by alefragnani** [comment]
Hi @blacksunrise56 ,

There is no reason for that, except that's how the original TextMate package is defined, as you can check in the [repo](https://github.com/textmate/pascal.tmbundle/blob/master/Preferences/Miscellaneous.tmPreferences) 😄 .

 This really should be fixed. I will use your pull request to fix it. Thanks 👍
