### ISSUE TITLE
Some issue with highlighting in pascal sources

### ISSUE THREAD

**Issue by vv7v7** [alefragnani/atom-language-pascal#22]
Dear developer,
As you see at the picture below there's some issue with pascal's highlighting:

![screenshot_20171101_141550](https://user-images.githubusercontent.com/25136754/32274379-3952abca-bf0f-11e7-9bf0-51234680fb07.png)

So symbols **--** shouldn't be read as comment's start as in pascal's programming language

By the way thank you very much as needed for this type of plugin,

Best regards,
vv7v7

**Comment by alefragnani** [comment]
Hi @vv7v7 ,

That's weird. I never noted that before. In fact, looking at the source that I used to create this syntax (Textmate), it appears that is already there. I don't know if that's something that comes from FreePascal/Lazarus, but I'll take a look.

Thanks for reporting 👍
