### ISSUE TITLE
Function highlighting in recusion

### ISSUE THREAD

**Issue by crazydiver** [alefragnani/atom-language-pascal#24]
Hi,
Are there any ways to highlight function name in recursion function like in the code?

`procedure find(const matr :masmas; var visited : masBool; const n, vert, cur : longint; k : longint; var cntr : longint);

var
  i : longint;
begin
  visited[cur] := true;
  if k=1 then
    begin
      if matr[cur, vert]=1 then
        cntr+=1;
    end
  else
    for i:=1 to n do
      if (matr[cur, i] <> 0) and (not visited[i]) then
        find(matr, visited, n, vert, i, k-1, cntr);
  visited[cur] := false;
end;
`
PS. Sorry for no tabs in code, but Github refuses to put it there

**Comment by alefragnani** [comment]
Hi @crazydiver ,

I’m sorry, but unfortunately no. At least, not using the current _textmate grammar approach_.

Hope this helps
