### ISSUE TITLE
Hard-coded tab length

### ISSUE THREAD

**Issue by corentin-cdf** [alefragnani/atom-language-pascal#27]
The tab length is hard-coded to 2 in the settings, and that prevented me from setting it to 4 until I went into the code of the plugin to change it.
Atom's settings interface wouldn't let me change it to 4 (whereas it works for 8 for example), because for some reason it considers 4 to be default (even within the plugin), so I guess typing "4" was interpreted as setting to default (while in fact, the default value was 2 as I mentioned earlier).

**Comment by alefragnani** [comment]
Hi @corentin-cdf ,

It appears you are having the same issue reported in #20 , which is in fact, an _Atom_ issue.

As describe in [this comment](https://github.com/alefragnani/atom-language-pascal/issues/20#issuecomment-331030203), you must update your `config.cson` file _manually_, with the following lines:

```
".pascal.source":
  editor:
    tabLength: 4
```

After that, your TABs will work as expected

Hope this helps

ps: Please, report this UI issue in atom repository...
